package net.csdn.jpa.query;

/**
 * Renders the companion source and the package anchor source.
 * Values never appear in either file.
 */
final class QuerySources {

    static final String ANCHOR_SIMPLE_NAME = "ServiceFrameworkPackageAnchor";
    static final String GENERATED_BY = "net.csdn.jpa.query.ServiceFrameworkQueryProcessor";

    private QuerySources() {
    }

    static String companionSimpleName(String modelSimpleName) {
        return modelSimpleName + "Queries";
    }

    static String companionSource(String packageName, String modelSimpleName, QueryMetadata metadata) {
        String source = renderCompanion(packageName, modelSimpleName, metadata);
        if (source.length() > QueryLimits.MAX_GENERATED_SOURCE_CHARS) {
            throw new QueryDeclarationException(metadata.getModelName(), "-", "-",
                    "generated source length " + source.length() + " exceeds " + QueryLimits.MAX_GENERATED_SOURCE_CHARS);
        }
        return source;
    }

    static String anchorSource(String packageName) {
        StringBuilder source = new StringBuilder(256);
        source.append("package ").append(packageName).append(";\n\n");
        source.append("// Generated by ").append(GENERATED_BY).append(". Do not edit.\n");
        source.append("// Same-package anchor for JDK 17 class definition.\n");
        source.append("// Not a query API. Do not use it to resolve query metadata or as a ClassDefiner lookup key beyond the neighbor Class itself.\n\n");
        source.append("public final class ").append(ANCHOR_SIMPLE_NAME).append(" {\n");
        source.append("    private ").append(ANCHOR_SIMPLE_NAME).append("() {\n");
        source.append("    }\n");
        source.append("}\n");
        return source.toString();
    }

    private static String renderCompanion(String packageName, String modelSimpleName, QueryMetadata metadata) {
        String modelType = packageName + "." + modelSimpleName;
        String companion = companionSimpleName(modelSimpleName);
        StringBuilder source = new StringBuilder(512);
        source.append("package ").append(packageName).append(";\n\n");
        source.append("// Generated by ").append(GENERATED_BY).append(". Do not edit.\n");
        source.append("// Declarative companion for ").append(modelType).append(".\n");
        source.append("// This is not a dynamic finder and it does not add methods to the model.\n");
        source.append("// Methods:");
        for (int i = 0; i < metadata.getMethods().size(); i++) {
            source.append(' ').append(metadata.getMethods().get(i).getMethodName());
        }
        source.append("\n\n");
        source.append("public final class ").append(companion).append(" {\n");
        source.append("    private ").append(companion).append("() {\n");
        source.append("    }\n");
        for (int i = 0; i < metadata.getMethods().size(); i++) {
            source.append('\n');
            appendMethod(source, modelType, metadata.getMethods().get(i));
        }
        source.append("}\n");
        return source.toString();
    }

    private static void appendMethod(StringBuilder source, String modelType, QueryDescriptor method) {
        appendMethod(source, modelType, method, false);
        source.append('\n');
        appendMethod(source, modelType, method, true);
    }

    /**
     * Renders one overload. Parameters are {@code p0}, {@code p1}, ... — the same
     * stable names the descriptor assigns to bind parameters — so a model field
     * named {@code offset}, {@code limit} or {@code entityManager} still compiles.
     * With {@code explicitEntityManager} the caller's own EntityManager is used;
     * without it the executor resolves the JPA context EntityManager.
     */
    private static void appendMethod(StringBuilder source, String modelType, QueryDescriptor method, boolean explicitEntityManager) {
        source.append("    public static java.util.List<").append(modelType).append("> ");
        source.append(method.getMethodName()).append('(');
        if (explicitEntityManager) {
            source.append("javax.persistence.EntityManager entityManager, ");
        }
        for (int i = 0; i < method.getPredicates().size(); i++) {
            QueryPredicate predicate = method.getPredicates().get(i);
            if (i > 0) {
                source.append(", ");
            }
            source.append(sourceType(predicate)).append(' ').append(predicate.getParameterName());
        }
        if (!method.getPredicates().isEmpty()) {
            source.append(", ");
        }
        source.append("int offset, int limit) {\n");
        source.append("        return net.csdn.jpa.query.GeneratedQueryExecutor.execute(");
        if (explicitEntityManager) {
            source.append("entityManager, ");
        }
        source.append(modelType).append(".class, \"").append(method.getMethodName()).append("\", new Object[]{");
        for (int i = 0; i < method.getPredicates().size(); i++) {
            if (i > 0) {
                source.append(", ");
            }
            source.append(method.getPredicates().get(i).getParameterName());
        }
        source.append("}, offset, limit);\n");
        source.append("    }\n");
    }

    private static String sourceType(QueryPredicate predicate) {
        return predicate.getJavaType();
    }
}
